name: jaffle_shop

profile: jaffle_shop

seed-paths: ['seeds']
model-paths: ['models']
macro-paths: ['macros']
clean-targets:
  - 'target'
  - 'dbt_packages'

seeds:
  jaffle_shop:
    +schema: raw

on-run-start:
  - 'CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log ( model_name STRING, run_timestamp TIMESTAMP )'

models:
  +post-hook:
    - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)"
  +grants:
    select: ['transform', 'reporter']
  jaffle_shop:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table

data_tests:
  +store_failures: true
  +schema: test_failures
